apiVersion: v1
kind: Service
metadata:
  name: sa-backend-service
spec:
  # NodePort = pour tester en local (accès depuis l’extérieur du cluster).
  # ClusterIP = uniquement interne cluster.
  type: NodePort
  selector:
    app: sa-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # ex. accessible sur http://localhost:30080 si Docker Desktop
